# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

minApprovals:
  COLLABORATOR: 1
maxRequestedChanges:
  NONE: 0
updateBranch: true
deleteBranchAfterMerge: true
blockingLabels:
  - blocked
